-- Populate "What We Do" related tables with existing hardcoded data
-- Run this after creating the tables with create-what-we-do-tables.sql

-- Insert Our Approach Departments
INSERT INTO our_approach_departments (title, description, icon_name, key_activities, display_order) VALUES
('Research & Development', 'Generating evidence to inform policy, practice, and innovation through comprehensive research and analysis across all sectors.', 'BookOpen', ARRAY['Documentation and Think tanks', 'Policy Analysis and Legislative Scrutiny', 'Experiments and Implementation', 'Kimeeza / Public debates'], 1),
('Training & Skill Development', 'Equipping young people and communities with digital, technical, and rights-based skills for the digital transformation era.', 'Users', ARRAY['Short courses and Academic programmes', 'Seminars and Master classes', 'Webinars and Workshops', 'Capacity building initiatives'], 2),
('Advocacy & Partnerships', 'Building alliances to influence policy and amplify voices for justice and accountability across Africa.', 'Megaphone', ARRAY['Reporting and MDA collaborations', 'Activism and Strategic litigation', 'ADR and Legislative drafting', 'Coalition/Networks/Movement building'], 3),
('Tech, Innovation & Digital Transformation (TID)', 'Creating and supporting solutions that harness technology for inclusive and sustainable development.', 'Lightbulb', ARRAY['Hackathons and IP Protection', 'Data management and Sandboxes', 'Compliance services', 'Grant & Donations and Investment Fund'], 4);

-- Insert Our Services (ServicesComponent data)
INSERT INTO our_services (title, description, icon_name, services, display_order) VALUES
('Research & Development', 'Comprehensive research and analysis including feasibility studies, impact assessments, legislative scrutiny, and expert legal and policy analysis', 'BookOpen', ARRAY['Feasibility studies', 'Impact assessments', 'Legislative scrutiny', 'Policy analysis', 'Market research', 'Technical documentation'], 1),
('Training & Capacity Building', 'Specialized training programs covering research methodology, academic writing, and tailored courses on contemporary issues', 'Users', ARRAY['Research methodology training', 'Academic writing workshops', 'Professional development courses', 'Customized training programs', 'Online learning modules', 'Certification programs'], 2),
('Compliance & Legal Services', 'Navigate legal landscapes with audits, documentation, and reporting. Specializing in data protection and privacy compliance', 'Shield', ARRAY['Compliance audits', 'Legal documentation', 'Privacy assessments', 'Data protection consulting', 'Regulatory guidance', 'Risk management'], 3),
('Corporate & Intellectual Property', 'Comprehensive corporate law services including intellectual property protection, mergers, acquisitions, and business structuring', 'Building', ARRAY['IP protection and registration', 'Corporate structuring', 'Mergers & acquisitions', 'Contract drafting and review', 'Business licensing', 'Commercial negotiations'], 4),
('Strategic Consulting', 'High-level strategic guidance for organizations navigating the intersection of technology, law, and policy in Africa', 'TrendingUp', ARRAY['Digital transformation strategy', 'Technology policy development', 'Stakeholder engagement planning', 'Change management', 'Innovation strategy', 'Market entry consulting'], 5),
('Litigation & Advocacy', 'Expert representation in technology-related disputes and advocacy for digital rights and policy reform', 'Scale', ARRAY['Strategic litigation', 'Digital rights advocacy', 'Policy reform campaigns', 'Dispute resolution', 'Regulatory representation', 'Public interest litigation'], 6);

-- Insert Services Offerings (Services component data)
INSERT INTO services_offerings (title, description, icon_name, features, benefits, color, border_color, display_order) VALUES
('Hackathon Program', 'Supporting innovations that propel the wellbeing of people living on the continent.', 'Trophy', ARRAY['Financial support for developers and startups', 'Legal guidance and intellectual property protection', 'Technical mentorship and development support', 'Focus on digital health, fintech, AgriTech, education and transport'], ARRAY['Up to $50,000 funding', '6-month mentorship', 'Legal protection', 'Market access'], 'from-yellow-500/20 to-orange-500/20', 'border-yellow-500/30', 1),
('Legal & Regulatory Support', 'Comprehensive legal guidance for tech companies navigating Africa''s regulatory landscape.', 'Scale', ARRAY['Regulatory compliance assessment and guidance', 'Intellectual property protection and licensing', 'Data protection and privacy law compliance', 'Contract drafting and technology agreements'], ARRAY['Expert legal team', 'Regulatory compliance', 'IP protection', 'Risk mitigation'], 'from-blue-500/20 to-indigo-500/20', 'border-blue-500/30', 2),
('Research & Training', 'Cutting-edge research and professional development in technology law and policy.', 'BookOpen', ARRAY['Technology law research and policy development', 'Professional training and certification programs', 'Industry reports and white papers', 'Capacity building for legal professionals'], ARRAY['Industry insights', 'Professional certification', 'Skill development', 'Knowledge access'], 'from-green-500/20 to-teal-500/20', 'border-green-500/30', 3),
('Strategic Advocacy', 'Influencing policy and regulatory frameworks to support innovation and human rights.', 'Megaphone', ARRAY['Policy advocacy and regulatory reform initiatives', 'Stakeholder engagement and public consultation', 'Rights-based approach to technology governance', 'International cooperation and best practice sharing'], ARRAY['Policy influence', 'Stakeholder access', 'Rights protection', 'Global network'], 'from-purple-500/20 to-pink-500/20', 'border-purple-500/30', 4);

-- Insert Service Highlights
INSERT INTO service_highlights (title, description, icon_name, display_order) VALUES
('Expert Team', 'Access to experienced tech lawyers and industry specialists', 'Users', 1),
('Comprehensive Support', 'End-to-end solutions for your tech venture', 'CheckCircle', 2),
('Protection & Compliance', 'Ensuring your innovation is legally protected', 'Shield', 3),
('Quality Assurance', 'Rigorous standards in all our services', 'Star', 4);

-- Insert Areas of Work
INSERT INTO areas_of_work (title, description, icon_name, features, color, border_color, display_order) VALUES
('Health', 'Innovating digital health solutions to enhance healthcare delivery and accessibility across Africa, focusing on telemedicine, health data protection, and medical AI regulation.', 'Heart', ARRAY['Digital Health Platforms', 'Medical Data Privacy', 'Telemedicine Regulation', 'AI in Healthcare'], 'from-red-500/20 to-pink-500/20', 'border-red-500/30', 1),
('Agriculture', 'Developing AgriTech solutions to improve farming practices and food security, including smart farming technologies, agricultural data management, and supply chain optimization.', 'Sprout', ARRAY['Smart Farming Tech', 'Agricultural Data', 'Supply Chain', 'Precision Agriculture'], 'from-green-500/20 to-emerald-500/20', 'border-green-500/30', 2),
('Finance', 'Creating fintech innovations to promote financial inclusion and economic growth, covering cryptocurrency regulation, digital banking, and mobile payment systems.', 'Banknote', ARRAY['Digital Banking', 'Cryptocurrency Law', 'Mobile Payments', 'Financial Inclusion'], 'from-blue-500/20 to-cyan-500/20', 'border-blue-500/30', 3),
('Education', 'Implementing EdTech solutions to make quality education more accessible and effective, including online learning platforms, educational data protection, and digital literacy.', 'GraduationCap', ARRAY['E-Learning Platforms', 'Educational Data', 'Digital Literacy', 'Remote Education'], 'from-purple-500/20 to-violet-500/20', 'border-purple-500/30', 4),
('Transport', 'Developing smart transportation solutions to improve mobility and logistics, including autonomous vehicles, smart traffic systems, and logistics optimization.', 'Truck', ARRAY['Smart Traffic', 'Autonomous Vehicles', 'Logistics Tech', 'Urban Mobility'], 'from-orange-500/20 to-yellow-500/20', 'border-orange-500/30', 5);

-- Insert Strategic Pillars
INSERT INTO strategic_pillars (title, description, icon_name, items, display_order) VALUES
('Research', 'Evidence-based insights and analysis to inform policy and practice', 'Target', ARRAY['Documentation', 'Think tanks', 'Experiments', 'Policy Analysis', 'Legislative Scrutiny', 'Kimeeza / Public debates', 'Implementation'], 1),
('Training', 'Building capacity across all levels of the ecosystem', 'Users', ARRAY['Short courses', 'Academic programmes', 'Seminars', 'Master classes', 'Webinars'], 2),
('Advocacy', 'Driving policy change and legal reform through strategic engagement', 'Briefcase', ARRAY['Reporting', 'MDA collaborations', 'Activism', 'Litigation', 'ADR', 'Legislative drafting', 'Coalition/Networks/Movement'], 3),
('Innovation', 'Creating and supporting solutions that harness technology for inclusive development', 'Lightbulb', ARRAY['Hackathons', 'IP Protection', 'Data management', 'Sandboxes', 'Compliance services', 'Grant & Donations', 'Investment Fund'], 4);