#!/bin/bash

echo "=========================================="
echo "SUPABASE STORAGE BUCKET SETUP GUIDE"
echo "=========================================="
echo ""
echo "Your application uses ONE main storage bucket called 'images'"
echo "for all image uploads across different sections."
echo ""
echo "REQUIRED STORAGE BUCKET:"
echo "• Bucket Name: images"
echo "• Public Access: YES (required for web display)"
echo ""
echo "SECTIONS THAT USE THIS BUCKET:"
echo "• Team Members (team member photos)"
echo "• Hero Slides (hero section images)"
echo "• News Updates (featured images)"
echo "• Blogs (blog post images)"
echo "• Resources (resource images)"
echo "• Products (product images)"
echo "• Research Publications (publication images)"
echo "• Research Experts (expert photos)"
echo "• Home Sections (section images)"
echo "• Footer (footer images)"
echo ""
echo "=========================================="
echo "STEP-BY-STEP SETUP INSTRUCTIONS:"
echo "=========================================="
echo ""
echo "1. Go to your Supabase Dashboard:"
echo "   https://supabase.com/dashboard"
echo ""
echo "2. Select your project:"
echo "   uokhrvetwffiyapivjjf"
echo ""
echo "3. Click on 'Storage' in the left sidebar"
echo ""
echo "4. Click the 'Create bucket' button"
echo ""
echo "5. Configure the bucket:"
echo "   • Name: images"
echo "   • Public bucket: CHECK THIS BOX ✓"
echo "   • Click 'Create bucket'"
echo ""
echo "6. The bucket is now ready for use!"
echo ""
echo "=========================================="
echo "TESTING THE BUCKET:"
echo "=========================================="
echo ""
echo "After creating the bucket, try adding a team member"
echo "in the admin panel. The image upload should now work."
echo ""
echo "If you still get errors, check:"
echo "• Bucket name is exactly 'images' (lowercase)"
echo "• Public access is enabled"
echo "• Your Supabase project has proper permissions"
echo ""
echo "=========================================="